# Generated by Django 4.2.16 on 2024-10-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='serial_carroceria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='serial_motor',
            field=models.CharField(max_length=50),
        ),
    ]
